"use client";
import { useId, useState } from "react";
import { Illustration } from "./illustration";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowUpRight, ArrowRight, CalendarDays, ChevronRight, CircleDollarSign, GraduationCap, RotateCcw, UsersRound, Download, Clock3, Check, Sparkles, Upload, CircleCheck, MoreHorizontal, TrendingUp } from "lucide-react";
import { useData, workspaceAccess, canWorkRecord, canVisitPage } from "./provider";
import { Avatar, Badge, Button, EmptyState, PageHeading, PanelHeader, Score, TextLink, Dialog, Field, download } from "./ui";
import { type Workspace, type RevenueSeriesPoint, revenueReport, currency, dateLabel, revenueSeries, recoverableLeads, STAGES, relativeTime, csvCell } from "@/lib/domain";

export function RangeSelect({ value, onChange }: { value: number; onChange: (value: number) => void }) {
  return <label className="range-select"><CalendarDays size={15} /><span className="sr-only">Report period</span><select value={value} onChange={event => onChange(Number(event.target.value))}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select></label>;
}
export function RevenueChart({ workspace, days, metric = "revenue", series }: { workspace: Workspace; days: number; metric?: "revenue" | "admissions"; series?: RevenueSeriesPoint[] }) {
  const id = useId().replaceAll(":", "");
  const data = (series || revenueSeries(workspace, days)).map(point => ({ ...point, label: dateLabel(point.date, { month: "short", day: "numeric" }) }));
  return <div className="revenue-chart">
    <ResponsiveContainer width="100%" height={244} minWidth={0} initialDimension={{ width: 650, height: 244 }}>
      <AreaChart data={data} margin={{ top: 16, right: 12, left: -16, bottom: 0 }} accessibilityLayer>
        <defs><linearGradient id={id} x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="var(--color-accent)" stopOpacity={.2} /><stop offset="100%" stopColor="var(--color-accent)" stopOpacity={.015} /></linearGradient></defs>
        <CartesianGrid vertical={false} stroke="var(--color-rule)" strokeDasharray="3 4" />
        <XAxis dataKey="label" axisLine={false} tickLine={false} minTickGap={48} tick={{ fill: "var(--color-muted)", fontSize: 11 }} dy={8} />
        <YAxis axisLine={false} tickLine={false} tickCount={4} allowDecimals={metric === "revenue"} width={65} tick={{ fill: "var(--color-muted)", fontSize: 11 }} tickFormatter={value => metric === "revenue" ? currency(Number(value), true) : String(value)} />
        <Tooltip contentStyle={{ border: "1px solid var(--color-rule)", background: "var(--color-surface)", color: "var(--color-body)", borderRadius: 8, fontSize: 12, boxShadow: "var(--shadow-floating)" }} formatter={value => [metric === "revenue" ? currency(Number(value)) : value, metric === "revenue" ? "Collected revenue" : "Paid admissions"]} />
        <Area type="monotone" dataKey={metric === "revenue" ? "cumulative" : "count"} stroke="var(--color-accent)" strokeWidth={2.5} fill={`url(#${id})`} activeDot={{ r: 5, stroke: "var(--color-surface)", strokeWidth: 3 }} isAnimationActive={false} />
      </AreaChart>
    </ResponsiveContainer>
    <div className="chart-key"><span><i />{metric === "revenue" ? "Campaign-associated collections" : "Campaign-associated admissions"}</span><span>Cumulative · {metric === "revenue" ? "INR" : "students"}</span></div>
    <details className="chart-data"><summary>View chart data</summary><div className="chart-data-scroll"><table aria-label={metric === "revenue" ? "Recovery revenue by day" : "Recovery admissions by day"}><thead><tr><th>Date</th><th>{metric === "revenue" ? "Collected" : "New paid students"}</th><th>{metric === "revenue" ? "Cumulative" : "Cumulative paid students"}</th></tr></thead><tbody>{data.map(point => <tr key={point.date}><td>{point.label}</td><td>{metric === "revenue" ? currency(point.value) : point.newRecoveredAdmissions}</td><td>{metric === "revenue" ? currency(point.cumulative) : point.count}</td></tr>)}</tbody></table></div></details>
  </div>;
}
function MiniTrend({ values, colour = "var(--color-accent)" }: { values: number[]; colour?: string }) {
  const max = Math.max(1, ...values), min = Math.min(0, ...values);
  const points = values.map((value, i) => `${i * 90 / Math.max(1, values.length - 1)},${28 - (value - min) / Math.max(1, max - min) * 24}`).join(" ");
  return <svg className="mini-trend" viewBox="0 0 92 32" aria-hidden="true"><polyline points={points} fill="none" stroke={colour} strokeWidth="2" strokeLinejoin="round" strokeLinecap="round" /></svg>;
}

export function OverviewPage({ onNavigate, onOpen, onImport }: { onNavigate: (path: string) => void; onOpen: (id: string) => void; onImport: () => void }) {
  const { data, act } = useData();
  const { admin } = workspaceAccess(data);
  const [days, setDays] = useState(30), [chart, setChart] = useState<"revenue" | "admissions">("revenue");
  const report = revenueReport(data, days), numbers = report.totals, eligible = recoverableLeads(data);
  const upcoming = data.appointments.filter(item => item.status === "scheduled" && Date.parse(item.startsAt) >= Date.now()).sort((a, b) => a.startsAt.localeCompare(b.startsAt));
  const tasks = (data.tasks || []).filter(task => task.status === "open").sort((a, b) => a.dueAt.localeCompare(b.dueAt));
  const trend = report.series.filter((_, index) => index % Math.max(1, Math.floor(days / 12)) === 0).map(item => item.cumulative);
  const conversion = data.leads.length ? Math.round(data.leads.filter(lead => lead.stage === "Admitted").length / data.leads.length * 100) : 0;
  const stages = ["New", "Contacted", "Qualified", "Counselling", "Admitted"] as const;
  return <>
    <div className="page-eyebrow"><span>YOUR ADMISSIONS, AT A GLANCE</span><span>{dateLabel(new Date().toISOString(), { weekday: "short", day: "numeric", month: "long", year: "numeric" })}</span></div>
    <PageHeading title={`Your next chapter, ${(data.actor?.name || data.userName).split(" ")[0]}.`} description="A new day. A few thoughtful follow-ups. Your next admission."><RangeSelect value={days} onChange={setDays} />{admin && <Button action={{ type: "lead.import" }} variant="primary" onClick={onImport}><Upload size={15} />Import enquiries</Button>}</PageHeading>
    <section className="metrics-grid" aria-label="Admission metrics">
      <article className="metric-card"><div className="metric-label"><span className="metric-icon blue-icon"><CircleDollarSign size={16} /></span><span>Recovered revenue</span><ArrowUpRight size={15} /></div><div className="metric-value-line"><strong className="metric-number">{currency(numbers.recoveredRevenue)}</strong><MiniTrend values={trend} /></div><div className="metric-foot"><span className="metric-change"><CircleCheck size={12} />Collected</span><span>from {numbers.recoveredAdmissions} admissions</span></div></article>
      <article className="metric-card"><div className="metric-label"><span className="metric-icon violet-icon"><UsersRound size={16} /></span><span>Total enquiries</span><ArrowUpRight size={15} /></div><div className="metric-value-line"><strong className="metric-number">{data.leads.length}</strong><span className="metric-soft-number">students</span></div><div className="metric-foot"><span className="metric-change blue-text">{eligible.length} ready</span><span>for a fresh conversation</span></div></article>
      <article className="metric-card"><div className="metric-label"><span className="metric-icon green-icon"><GraduationCap size={16} /></span><span>Paid admissions</span><ArrowUpRight size={15} /></div><div className="metric-value-line"><strong className="metric-number">{numbers.admissions}</strong><div className="mini-bars" aria-hidden="true">{stages.map(stage => <i key={stage} style={{ height: `${8 + data.leads.filter(lead => lead.stage === stage).length * 3}px` }} />)}</div></div><div className="metric-foot"><span className="metric-change">{conversion}%</span><span>of the current enquiry base</span></div></article>
      <article className="metric-card"><div className="metric-label"><span className="metric-icon amber-icon"><CalendarDays size={16} /></span><span>Upcoming sessions</span><ArrowUpRight size={15} /></div><div className="metric-value-line"><strong className="metric-number">{upcoming.length.toString().padStart(2, "0")}</strong><div className="avatar-stack">{data.team.slice(0, 3).map(name => <Avatar key={name} name={name} small />)}</div></div><div className="metric-foot"><span className="mini-dot amber" /><span>Your team’s next opportunities</span></div></article>
    </section>
    <div className="dashboard-grid main-dashboard-grid">
      <section className="panel performance-panel"><PanelHeader title="Small conversations. Real outcomes." description="A clear view of your recovery performance." action={canVisitPage(data, "analytics") && <button className="quiet-icon" aria-label="Open revenue analytics" onClick={() => onNavigate("analytics")}><ArrowUpRight size={17} /></button>} /><div className="chart-overview"><div><strong>{chart === "revenue" ? currency(numbers.recoveredRevenue) : numbers.recoveredAdmissions}</strong><span>{chart === "revenue" ? "collected through recovery" : "paid recovery admissions"}</span></div><div className="segmented-control"><button className={chart === "revenue" ? "active" : ""} aria-pressed={chart === "revenue"} onClick={() => setChart("revenue")}>Revenue</button><button className={chart === "admissions" ? "active" : ""} aria-pressed={chart === "admissions"} onClick={() => setChart("admissions")}>Admissions</button></div></div><RevenueChart workspace={data} days={days} metric={chart} series={report.series} /></section>
      <div className="dashboard-side"><section className="assistant-card"><div className="assistant-card-top"><span className="assistant-label"><Sparkles size={14} />ADMITFLOW INTELLIGENCE</span><span className="assistant-status"><i />{data.demo ? "Demo" : data.ai?.mode === "autonomous" ? "Autonomous" : data.ai?.mode === "paused" ? "Paused" : "Assisted"}</span></div><Illustration name="knowledge-observatory" className="assistant-art" decorative /><h2>A little ahead.<br />Always on your side.</h2><p>Your institute’s knowledge, ready for the next conversation.</p><div className="assistant-card-stats"><span><strong>{data.articles.length}</strong>knowledge sources</span><span><strong>{data.leads.filter(lead => !lead.humanOwned && !["Admitted", "Lost"].includes(lead.stage)).length}</strong>AI-owned enquiries</span></div><button onClick={() => onNavigate(admin ? "automations" : "inbox")}>{admin ? "Meet your assistant" : "Open your shared inbox"}<ArrowUpRight size={15} /></button></section>{canVisitPage(data, "recovery") && <button className="recovery-nudge" onClick={() => onNavigate("recovery")}><span className="nudge-icon"><RotateCcw size={19} /></span><span><strong>{eligible.length} conversations worth restarting</strong><small>Your next admission could be here.</small></span><ArrowRight size={16} /></button>}</div>
    </div>
    <div className="dashboard-grid bottom-grid">
      <section className="panel priority-panel"><PanelHeader title="A good place to start" description="The enquiries that deserve your attention today." action={<TextLink onClick={() => onNavigate("leads")}>All enquiries</TextLink>} />
        {eligible.length ? <><div className="priority-table-head"><span>STUDENT</span><span>NEXT STEP</span><span>INTENT</span></div><div className="recovery-shortlist">{eligible.slice(0, 4).map(lead => <button key={lead.id} onClick={() => onOpen(lead.id)} className="shortlist-row"><Avatar name={lead.name} /><span className="shortlist-name"><strong>{lead.name}</strong><small>{lead.course}</small></span><span className="shortlist-action"><span>{lead.nextAction}</span><small><Clock3 size={11} />{lead.lastContactAt ? relativeTime(lead.lastContactAt) : "No contact yet"}</small></span><Score lead={lead} /><ChevronRight size={15} /></button>)}</div><button className="panel-bottom-link" onClick={() => onNavigate(canVisitPage(data, "recovery") ? "recovery" : "leads")}>{canVisitPage(data, "recovery") ? "Find your next recovery opportunity" : "View your assigned enquiries"}<ArrowRight size={15} /></button></> : <EmptyState title="A fresh start" body="Your priority enquiries will appear here." action={admin && <Button action={{ type: "lead.import" }} onClick={onImport}>Import enquiries</Button>} />}
      </section>
      <section className="panel schedule-panel"><PanelHeader title="The next hello" description="Counselling sessions on your calendar." action={<button className="quiet-icon" aria-label="Open counselling calendar" onClick={() => onNavigate("appointments")}><CalendarDays size={17} /></button>} />
        {upcoming.length ? <div className="mini-schedule">{upcoming.slice(0, 3).map(appointment => { const lead = data.leads.find(item => item.id === appointment.leadId); return <button key={appointment.id} onClick={() => onOpen(appointment.leadId)}><span className="schedule-date"><strong>{dateLabel(appointment.startsAt, { day: "2-digit" })}</strong><small>{dateLabel(appointment.startsAt, { month: "short" })}</small></span><span className="schedule-person"><strong>{lead?.name || "Student"}</strong><small>{appointment.kind} · {dateLabel(appointment.startsAt, { hour: "numeric", minute: "2-digit" })}</small><span><Avatar name={appointment.owner} small />{appointment.owner.split(" ")[0]}</span></span><ArrowUpRight size={14} /></button>; })}</div> : <EmptyState title="Room for a new conversation" body="Book counselling from any enquiry." />}
        <button className="panel-bottom-link" onClick={() => onNavigate("appointments")}>View your calendar<ArrowRight size={15} /></button>
      </section>
    </div>
    <section className="panel daily-tasks"><PanelHeader title="A few things to move forward" action={<Badge>{tasks.length} open tasks</Badge>} /><div className="task-strip">{tasks.slice(0, 3).map(task => {
      const lead = data.leads.find(item => item.id === task.leadId);
      return <div key={task.id}>{lead && canWorkRecord(data, lead) && <button className="task-check" aria-label={`Complete ${task.title}`} onClick={() => void act({ type: "task.complete", id: task.id })}><Check size={13} /></button>}<button className="task-detail" onClick={() => onOpen(task.leadId)}><strong>{task.title}</strong><small>{lead?.name} · <span className={Date.parse(task.dueAt) < Date.now() ? "overdue" : ""}>{dateLabel(task.dueAt)}</span></small></button><Avatar name={task.owner} small /></div>;
    })}{!tasks.length && <p className="muted">You’re all caught up. A nice place to be.</p>}</div></section>
    <footer className="page-footer"><span><span className="footer-mark">↗</span> Behind every enquiry, a next chapter.</span><span>{data.demo ? "Fictional sample data" : data.name} <i /> INR · Asia/Kolkata</span></footer>
  </>;
}

export function AnalyticsPage({ onOpen }: { onOpen: (id: string) => void }) {
  const { data, act, busy, notify } = useData();
  const { admin } = workspaceAccess(data);
  const [days, setDays] = useState(30), [course, setCourse] = useState(""), [refundId, setRefundId] = useState("");
  const leads = data.leads.filter(lead => !course || lead.course === course), ids = new Set(leads.map(lead => lead.id));
  const payments = data.revenue.filter(payment => ids.has(payment.leadId));
  const filtered = { ...data, leads, revenue: payments, refunds: data.refunds?.filter(refund => payments.some(payment => payment.id === refund.revenueId)) };
  const report = revenueReport(filtered, days), numbers = report.totals;
  const events = [...report.payments].sort((a, b) => Date.parse(b.recordedAt) - Date.parse(a.recordedAt) || b.id.localeCompare(a.id));
  const sources = [...new Set(leads.map(lead => lead.source))].map(source => ({ source, leads: leads.filter(lead => lead.source === source).length, revenue: events.filter(event => leads.find(lead => lead.id === event.leadId)?.source === source).reduce((sum, event) => sum + Math.round((event.amount + Number.EPSILON) * 100), 0) / 100 })).sort((a, b) => b.revenue - a.revenue);
  return <><div className="page-eyebrow"><span>MEASURE WHAT MATTERS</span></div><PageHeading title="Every outcome, accounted for." description="Follow the story from first enquiry to collected fees."><RangeSelect value={days} onChange={setDays} /><Button onClick={() => download(["student,amount,campaign,receipt,date", ...events.map(event => [data.leads.find(lead => lead.id === event.leadId)?.name, event.amount, data.campaigns.find(campaign => campaign.id === event.campaignId)?.name || "Direct", event.reference, event.recordedAt].map(csvCell).join(","))].join("\r\n"), "admitflow-revenue.csv")}><Download size={15} />Export report</Button></PageHeading>
    <div className="analytics-summary"><div><span>Collected fees</span><strong>{currency(numbers.grossRevenue)}</strong><small>Recorded and provider-confirmed payments</small></div><div><span>Refunds</span><strong>{currency(numbers.totalRefunds)}</strong><small>Reconciled in this reporting period</small></div><div><span>Net revenue</span><strong className="blue-text">{currency(numbers.totalRevenue)}</strong><small>Collections less refunds</small></div><div><span>Paid admissions</span><strong>{numbers.admissions}</strong><small>{numbers.recoveredAdmissions} associated with recovery</small></div></div>
    <div className="analytics-grid"><section className="panel"><PanelHeader title="Recovery revenue" description="Cumulative campaign-associated collections, net of refunds." action={<label className="compact-select"><span className="sr-only">Report course</span><select value={course} onChange={event => setCourse(event.target.value)}><option value="">All courses</option>{data.courses.map(value => <option key={value}>{value}</option>)}</select></label>} /><RevenueChart workspace={filtered} days={days} series={report.series} /></section><section className="panel"><PanelHeader title="Where the momentum starts" description="Collected fees by enquiry source" /><div className="source-report">{sources.map((source, index) => <div key={source.source}><span className={`source-icon source-${index}`}>{source.source.slice(0, 1)}</span><div><strong>{source.source}</strong><small>{source.leads} enquiries</small><span className="source-track"><i style={{ width: `${numbers.grossRevenue ? source.revenue / numbers.grossRevenue * 100 : 0}%` }} /></span></div><strong>{currency(source.revenue, true)}</strong></div>)}</div></section></div>
    <section className="panel payments-panel"><PanelHeader title="The payment ledger" description="A clear reference behind every number." action={<Badge>{events.length} payments</Badge>} /><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Student</th><th>Receipt reference</th><th>Attribution</th><th>Date</th><th>Amount</th><th>Status</th><th /></tr></thead><tbody>{events.map(event => { const lead = data.leads.find(lead => lead.id === event.leadId); return <tr key={event.id}><td><button className="person-cell" onClick={() => onOpen(event.leadId)}><Avatar name={lead?.name || "Student"} small /><strong>{lead?.name || "Student"}</strong></button></td><td className="mono-text">{event.reference}</td><td>{data.campaigns.find(item => item.id === event.campaignId)?.name || "Direct"}</td><td>{dateLabel(event.recordedAt)}</td><td className="amount-cell">{currency(event.amount)}</td><td><Badge tone={event.origin === "razorpay" ? "green" : "neutral"}>{event.origin === "razorpay" ? "Verified" : "Recorded"}</Badge></td><td>{admin && event.origin !== "razorpay" && <button className="table-text-action" onClick={() => setRefundId(event.id)}>Refund</button>}</td></tr>; })}</tbody></table></div>{!events.length && <EmptyState title="Your first admission belongs here" body="Recorded payments and reconciled collections appear here." />}</section>
    <p className="field-note analytics-footnote">Campaign association shows which enquiries took part in recovery. Measuring incremental lift requires a comparison cohort.</p>
    {admin && refundId && <Dialog title="Record an offline refund" onClose={() => setRefundId("")}><p className="dialog-intro">Record money already refunded against this receipt.</p><form onSubmit={async event => { event.preventDefault(); const form = new FormData(event.currentTarget); const result = await act({ type: "revenue.refund", revenueId: refundId, amount: Number(form.get("amount")), reference: form.get("reference") }); if (result) { setRefundId(""); notify("Refund recorded and revenue updated."); } }}><Field name="amount" label="Refund amount (₹)" type="number" min="0.01" step="0.01" required /><Field name="reference" label="Refund reference" required /><div className="dialog-actions"><Button onClick={() => setRefundId("")}>Cancel</Button><Button variant="primary" type="submit" loading={busy}>Record refund</Button></div></form></Dialog>}
  </>;
}
